import Link from 'next/link';
import { ArrowLeft, Users } from 'lucide-react';

export default function CommunityPage() {
    return (
        <div className="min-h-screen bg-black text-white font-sans selection:bg-purple-500/30">
            {/* Header */}
            <header className="fixed top-0 left-0 right-0 z-50 border-b border-white/10 bg-black/50 backdrop-blur-md">
                <div className="container mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
                            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
                                <span className="text-white font-bold text-sm">♫</span>
                            </div>
                            <span className="font-bold text-lg tracking-tight">Opentunes.ai</span>
                        </Link>
                    </div>

                    <nav className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-400">
                        <Link href="/studio" className="hover:text-white transition-colors">Studio</Link>
                        <Link href="/community" className="text-white">Community</Link>
                    </nav>

                    <div className="flex items-center gap-4">
                        <Link href="/studio" className="px-4 py-2 text-sm font-medium bg-white text-black rounded-full hover:bg-gray-200 transition-colors">
                            Enter Studio
                        </Link>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="pt-32 container mx-auto px-6">
                <div className="text-center py-20">
                    <div className="w-16 h-16 mx-auto mb-6 rounded-full bg-white/10 flex items-center justify-center">
                        <Users className="w-8 h-8 text-purple-400" />
                    </div>
                    <h1 className="text-4xl md:text-6xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-b from-white to-gray-400">
                        Community Feed
                    </h1>
                    <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-10">
                        Explore the latest hits generated by the Opentunes ecosystem.
                        Remix, Fork, and Collaborate.
                    </p>

                    <div className="p-12 border border-dashed border-white/10 rounded-3xl bg-white/5">
                        <p className="text-gray-500 animate-pulse">Wait for Step 2... The feed is loading.</p>
                    </div>
                </div>
            </main>
        </div>
    );
}
